import type { AttackScenario, CallRecord, SecurityAlert } from "./types";

const today = (hh: number, mm: number) => {
  const d = new Date();
  d.setHours(hh, mm, 0, 0);
  return d.toISOString();
};

const daysAgo = (days: number, hh: number, mm: number) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hh, mm, 0, 0);
  return d.toISOString();
};

export const DEMO_CALLS: CallRecord[] = [
  {
    id: "CALL-90412",
    caller: "Rahul Mehta",
    callerId: "+91 98200 41288",
    timestamp: today(14, 32),
    language: "en",
    durationSeconds: 184,
    riskScore: 18,
    classification: "LOW_RISK",
    voiceType: "HUMAN",
    detection: "No manipulation indicators",
    action: "Allowed",
    status: "Safe",
  },
  {
    id: "CALL-90411",
    caller: "Unknown Caller",
    callerId: "+91 74009 55127",
    timestamp: today(14, 18),
    language: "hi",
    durationSeconds: 96,
    riskScore: 87,
    classification: "HIGH_RISK",
    voiceType: "AI_SUSPECTED",
    detection: "Synthetic speech indicators",
    action: "Blocked",
    status: "High Risk",
  },
  {
    id: "CALL-90409",
    caller: "CEO - Finance",
    callerId: "+91 90040 71190",
    timestamp: today(13, 52),
    language: "en",
    durationSeconds: 142,
    riskScore: 72,
    classification: "SUSPICIOUS",
    voiceType: "POSSIBLE_CLONE",
    detection: "Speaker mismatch",
    action: "Secondary verification",
    status: "Suspicious",
  },
  {
    id: "CALL-90405",
    caller: "Sneha Iyer",
    callerId: "+91 99400 21873",
    timestamp: today(12, 40),
    language: "ta",
    durationSeconds: 233,
    riskScore: 12,
    classification: "LOW_RISK",
    voiceType: "HUMAN",
    detection: "No manipulation indicators",
    action: "Allowed",
    status: "Safe",
  },
  {
    id: "CALL-90398",
    caller: "Vendor - Astra Supplies",
    callerId: "+91 80088 33021",
    timestamp: today(11, 26),
    language: "te",
    durationSeconds: 158,
    riskScore: 64,
    classification: "SUSPICIOUS",
    voiceType: "POSSIBLE_CLONE",
    detection: "Prosody irregularities",
    action: "Callback requested",
    status: "Verified",
  },
  {
    id: "CALL-90390",
    caller: "Govt Office - Revenue",
    callerId: "+91 70450 90014",
    timestamp: today(10, 5),
    language: "kn",
    durationSeconds: 121,
    riskScore: 76,
    classification: "SUSPICIOUS",
    voiceType: "AI_SUSPECTED",
    detection: "Neural vocoder artefacts",
    action: "Escalated",
    status: "Suspicious",
  },
  {
    id: "CALL-90371",
    caller: "Amit Bose",
    callerId: "+91 98300 55412",
    timestamp: daysAgo(1, 17, 12),
    language: "bn",
    durationSeconds: 275,
    riskScore: 22,
    classification: "LOW_RISK",
    voiceType: "HUMAN",
    detection: "No manipulation indicators",
    action: "Allowed",
    status: "Safe",
  },
  {
    id: "CALL-90366",
    caller: "Unknown Caller",
    callerId: "+91 63020 11784",
    timestamp: daysAgo(1, 15, 47),
    language: "hi",
    durationSeconds: 74,
    riskScore: 92,
    classification: "HIGH_RISK",
    voiceType: "POSSIBLE_SYNTHETIC",
    detection: "Voice cloning indicators",
    action: "Blocked",
    status: "Blocked",
  },
  {
    id: "CALL-90352",
    caller: "Priya Nair",
    callerId: "+91 94470 66127",
    timestamp: daysAgo(2, 12, 3),
    language: "ml",
    durationSeconds: 189,
    riskScore: 41,
    classification: "MEDIUM_RISK",
    voiceType: "HUMAN",
    detection: "Channel noise, inconclusive",
    action: "MFA requested",
    status: "Verified",
  },
  {
    id: "CALL-90341",
    caller: "Branch Manager - Pune",
    callerId: "+91 90280 74400",
    timestamp: daysAgo(2, 10, 22),
    language: "mr",
    durationSeconds: 205,
    riskScore: 29,
    classification: "LOW_RISK",
    voiceType: "HUMAN",
    detection: "No manipulation indicators",
    action: "Allowed",
    status: "Safe",
  },
  {
    id: "CALL-90333",
    caller: "Unknown Caller",
    callerId: "+91 88009 12456",
    timestamp: daysAgo(3, 19, 41),
    language: "en",
    durationSeconds: 88,
    riskScore: 84,
    classification: "HIGH_RISK",
    voiceType: "POSSIBLE_SYNTHETIC",
    detection: "Text-to-speech synthesis",
    action: "Blocked",
    status: "Blocked",
  },
  {
    id: "CALL-90325",
    caller: "Karthik Reddy",
    callerId: "+91 90000 33871",
    timestamp: daysAgo(4, 9, 15),
    language: "te",
    durationSeconds: 246,
    riskScore: 16,
    classification: "LOW_RISK",
    voiceType: "HUMAN",
    detection: "No manipulation indicators",
    action: "Allowed",
    status: "Safe",
  },
];

export const DEMO_ALERTS: SecurityAlert[] = [
  {
    id: "ALRT-4471",
    severity: "HIGH",
    title: "Possible CEO voice impersonation detected",
    message:
      "A caller presenting as CEO - Finance requested an urgent fund transfer of ₹8,50,000. Voice integrity score 87%.",
    callId: "CALL-90411",
    createdAt: today(14, 19),
    read: false,
    state: "open",
  },
  {
    id: "ALRT-4468",
    severity: "SUSPICIOUS",
    title: "Speaker consistency mismatch detected",
    message: "Speaker embedding drifted from the enrolled profile mid-call on CALL-90409.",
    callId: "CALL-90409",
    createdAt: today(13, 54),
    read: false,
    state: "open",
  },
  {
    id: "ALRT-4463",
    severity: "VERIFICATION",
    title: "High-value transaction requires secondary verification",
    message: "₹4,20,000 fund transfer requested on CALL-90398 while risk score was 64%.",
    callId: "CALL-90398",
    createdAt: today(11, 28),
    read: false,
    state: "open",
  },
  {
    id: "ALRT-4455",
    severity: "SUSPICIOUS",
    title: "Neural vocoder artefacts detected",
    message: "Government office caller flagged with spectral artefacts typical of synthesis.",
    callId: "CALL-90390",
    createdAt: today(10, 7),
    read: true,
    state: "escalated",
  },
  {
    id: "ALRT-4440",
    severity: "HIGH",
    title: "Voice cloning indicators on blocked call",
    message: "CALL-90366 was blocked automatically after a 92% impersonation risk score.",
    callId: "CALL-90366",
    createdAt: daysAgo(1, 15, 49),
    read: true,
    state: "resolved",
  },
];

export const THREAT_TIMELINE = [
  { hour: "00:00", safe: 18, suspicious: 2, highRisk: 0 },
  { hour: "02:00", safe: 11, suspicious: 1, highRisk: 1 },
  { hour: "04:00", safe: 7, suspicious: 1, highRisk: 0 },
  { hour: "06:00", safe: 22, suspicious: 3, highRisk: 1 },
  { hour: "08:00", safe: 58, suspicious: 6, highRisk: 2 },
  { hour: "10:00", safe: 96, suspicious: 11, highRisk: 3 },
  { hour: "12:00", safe: 104, suspicious: 9, highRisk: 2 },
  { hour: "14:00", safe: 118, suspicious: 14, highRisk: 5 },
  { hour: "16:00", safe: 88, suspicious: 8, highRisk: 3 },
  { hour: "18:00", safe: 61, suspicious: 7, highRisk: 2 },
  { hour: "20:00", safe: 34, suspicious: 4, highRisk: 1 },
  { hour: "22:00", safe: 25, suspicious: 3, highRisk: 1 },
];

export const THREATS_OVER_TIME = [
  { day: "Mon", threats: 9, calls: 178 },
  { day: "Tue", threats: 12, calls: 192 },
  { day: "Wed", threats: 7, calls: 165 },
  { day: "Thu", threats: 15, calls: 210 },
  { day: "Fri", threats: 18, calls: 233 },
  { day: "Sat", threats: 6, calls: 121 },
  { day: "Sun", threats: 4, calls: 96 },
];

export const DETECTION_CATEGORIES = [
  { category: "Voice Cloning", count: 19 },
  { category: "Synthetic Speech", count: 14 },
  { category: "Speaker Mismatch", count: 9 },
  { category: "Manipulated Audio", count: 5 },
];

export const LANGUAGE_DISTRIBUTION = [
  { language: "English", calls: 486 },
  { language: "Hindi", calls: 331 },
  { language: "Telugu", calls: 158 },
  { language: "Tamil", calls: 122 },
  { language: "Kannada", calls: 74 },
  { language: "Marathi", calls: 61 },
  { language: "Bengali", calls: 34 },
  { language: "Malayalam", calls: 18 },
];

export const RISK_DISTRIBUTION = [
  { name: "Low", value: 921, tone: "safe" as const },
  { name: "Medium", value: 244, tone: "medium" as const },
  { name: "Suspicious", value: 87, tone: "suspicious" as const },
  { name: "High", value: 32, tone: "critical" as const },
];

export const SCENARIOS: AttackScenario[] = [
  {
    id: "ceo-impersonation",
    title: "CEO Impersonation",
    summary: "Cloned executive voice pushing an urgent vendor payment.",
    caller: "CEO - Finance Department",
    callerId: "+91 90040 71190",
    transcript:
      "Please urgently transfer ₹8,50,000 to the new vendor account. I am travelling and cannot authorise it myself.",
    language: "en",
    expectedRisk: 92,
    context: {
      caller: "CEO - Finance Department",
      callerId: "+91 90040 71190",
      knownContact: false,
      transactionAmount: 850000,
      transactionType: "Fund Transfer",
      previousInteraction: "None",
      timeOfDay: "Unusual",
      historicalFraudIndicator: "Medium",
    },
  },
  {
    id: "bank-customer-clone",
    title: "Bank Customer Voice Clone",
    summary: "Synthetic customer voice attempting a beneficiary change.",
    caller: "Customer - A/C 9921",
    callerId: "+91 74009 55127",
    transcript: "मुझे अपने खाते का बेनिफिशियरी तुरंत बदलना है, ओटीपी मेरे पास नहीं आ रहा है।",
    language: "hi",
    expectedRisk: 84,
    context: {
      caller: "Customer - A/C 9921",
      callerId: "+91 74009 55127",
      knownContact: true,
      transactionAmount: 320000,
      transactionType: "Beneficiary Change",
      previousInteraction: "3 calls in 24 hours",
      timeOfDay: "Unusual",
      historicalFraudIndicator: "Medium",
    },
  },
  {
    id: "govt-official",
    title: "Government Official Impersonation",
    summary: "Caller claiming to be a revenue officer demanding a settlement.",
    caller: "Revenue Officer - District",
    callerId: "+91 70450 90014",
    transcript: "మీ ఖాతా తనిఖీలో ఉంది, వెంటనే సెటిల్‌మెంట్ చెల్లించండి.",
    language: "te",
    expectedRisk: 76,
    context: {
      caller: "Revenue Officer - District",
      callerId: "+91 70450 90014",
      knownContact: false,
      transactionAmount: 150000,
      transactionType: "Penalty Settlement",
      previousInteraction: "None",
      timeOfDay: "Business hours",
      historicalFraudIndicator: "High",
    },
  },
  {
    id: "genuine-caller",
    title: "Genuine Caller",
    summary: "Enrolled customer with a routine service request.",
    caller: "Rahul Mehta",
    callerId: "+91 98200 41288",
    transcript: "Hi, I would like to update the address on my savings account, please.",
    language: "en",
    expectedRisk: 12,
    context: {
      caller: "Rahul Mehta",
      callerId: "+91 98200 41288",
      knownContact: true,
      transactionAmount: 0,
      transactionType: "Profile Update",
      previousInteraction: "12 verified interactions",
      timeOfDay: "Business hours",
      historicalFraudIndicator: "Low",
    },
  },
];

export const DASHBOARD_METRICS = {
  callsAnalyzed: 1284,
  threatsDetected: 47,
  highRiskCalls: 12,
  detectionAccuracy: 94.7,
  avgRiskScore: 31.4,
};
