/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyzeRouteImport } from './routes/app.analyze'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppLiveRouteImport } from './routes/app.live'
import { Route as AppResultRouteImport } from './routes/app.result'
import { Route as AppVerificationRouteImport } from './routes/app.verification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzeRoute = AppAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppResultRoute = AppResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analyze': typeof AppAnalyzeRoute
  '/app/history': typeof AppHistoryRoute
  '/app/live': typeof AppLiveRoute
  '/app/result': typeof AppResultRoute
  '/app/verification': typeof AppVerificationRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/analyze': typeof AppAnalyzeRoute
  '/app/history': typeof AppHistoryRoute
  '/app/live': typeof AppLiveRoute
  '/app/result': typeof AppResultRoute
  '/app/verification': typeof AppVerificationRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analyze': typeof AppAnalyzeRoute
  '/app/history': typeof AppHistoryRoute
  '/app/live': typeof AppLiveRoute
  '/app/result': typeof AppResultRoute
  '/app/verification': typeof AppVerificationRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/analyze'
    | '/app/history'
    | '/app/live'
    | '/app/result'
    | '/app/verification'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/analyze'
    | '/app/history'
    | '/app/live'
    | '/app/result'
    | '/app/verification'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/analyze'
    | '/app/history'
    | '/app/live'
    | '/app/result'
    | '/app/verification'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyze': {
      id: '/app/analyze'
      path: '/analyze'
      fullPath: '/app/analyze'
      preLoaderRoute: typeof AppAnalyzeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live': {
      id: '/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/result': {
      id: '/app/result'
      path: '/result'
      fullPath: '/app/result'
      preLoaderRoute: typeof AppResultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verification': {
      id: '/app/verification'
      path: '/verification'
      fullPath: '/app/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyzeRoute: typeof AppAnalyzeRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLiveRoute: typeof AppLiveRoute
  AppResultRoute: typeof AppResultRoute
  AppVerificationRoute: typeof AppVerificationRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyzeRoute: AppAnalyzeRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLiveRoute: AppLiveRoute,
  AppResultRoute: AppResultRoute,
  AppVerificationRoute: AppVerificationRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
